name: Backend_CICD_Pipeline
on: workflow_dispatch

permissions:
    id-token: write
    contents: read

jobs:
  Terraform:
    name: terraform_job
    runs-on: self-hosted
    steps:
    - name: checkout
      uses: action/checkout@v4.3.1

    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: terraform init
      id: Init
      working-directory: backend
      run: terraform init -input=false

    - name: terraform fmt
      id: fmt
      working-directory: backend
      run: terraform fmt
    #   continue-on-error: true

    - name: terraform validate
      id: Validate
      working-directory: backend
      run: terraform validate -no-color

    - name: terraform plan
      id: Plan
      working-directory: backend
      run: terraform plan -no-color -input=false
      continue-on-error: true

    - name: terraform apply
      id: Apply
      if: github.ref == 'refs/heads/main'
      working-directory: backend
      run: terraform apply -auto-approve