name: UK_Dev_App_TodoApp_01

on: # workflow_dispatch
  push:
    branches:
      - main
      - 'releases/**'
      
permissions:
  id-token: write
  contents: read

jobs:
  Terraform_Init:
    name: Terraform Init Job
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v4.3.1

    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    
    - name: Terraform Init
      shell: pwsh
      working-directory: environment/dev
      env: 
        ARM_USE_OIDC: "true"
        ARM_DISABLE_CLI: "true"
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      run: terraform init -reconfigure -input=false

    - name: Terraform Fmt
      id: fmt
      working-directory: environment/dev
      run: terraform fmt
      continue-on-error: true

    - name: Terraform Validate
      id: Validate
      working-directory: environment/dev
      run: terraform validate -no-color

    - name: Terraform Plan
      id: Plan
      working-directory: environment/dev
      run: terraform plan -no-color -input=false
      continue-on-error: true
      env: 
        ARM_USE_OIDC: "true"
        ARM_DISABLE_CLI: "true"
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


  Terraform_Apply:
    name: Terraform Apply Job
    runs-on: self-hosted
    needs: Terraform_Init
    steps:
    - name: Checkout
      uses: actions/checkout@v4.3.1

    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: Terraform Init
      id: Init
      working-directory: environment/dev
      run: terraform init -input=false
      env: 
        ARM_USE_OIDC: "true"
        ARM_DISABLE_CLI: "true"
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Terraform Apply
      id: Apply
      if: github.ref == 'refs/heads/main'
      working-directory: environment/dev
      run: terraform apply -auto-approve
      env: 
        ARM_USE_OIDC: "true"
        ARM_DISABLE_CLI: "true"
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}