name: UK_Dev_App_TodoApp_01

on: #workflow_dispatch
  push:
    branches:
      - main
      - 'releases/**'
      
permissions:
  id-token: write
  contents: read

jobs:
  Terraform_Init:
    name: Terraform Init Job
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v4.3.1

    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Set Terraform OIDC environment variables
      run: |
        echo "ARM_DISABLE_CLI=true" >> $GITHUB_ENV
        echo "ARM_USE_OIDC=true" >> $GITHUB_ENV
        echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
        echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
        echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
        
    
        
     
    - name: Terraform Init
      id: Init
      working-directory: environment/dev
      run: terraform init -input=false

    - name: Terraform Fmt
      id: fmt
      working-directory: environment/dev
      run: terraform fmt
      # continue-on-error: true

    - name: Terraform Validate
      id: Validate
      working-directory: environment/dev
      run: terraform validate -no-color

    - name: Terraform Plan
      id: Plan
      working-directory: environment/dev
      run: terraform plan -no-color -input=false
      continue-on-error: true


  Terraform_Apply:
    name: Terraform Apply Job
    runs-on: self-hosted
    needs: Terraform_Init
    environment: Dev
    steps:
    - name: Checkout
      uses: actions/checkout@v4.3.1

    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
     
    - name: Terraform Init
      id: Init
      working-directory: environment/dev
      run: terraform init -input=false

    - name: Terraform Apply
      id: Apply
      if: github.ref == 'refs/heads/main'
      working-directory: environment/dev
      run: terraform apply -auto-approve
          
    
