name: UK_Dev_App_TodoApp_01

on:
  push:
    branches:
      - main
      - 'releases/**'
permissions:
  id-token: write
  contents: read

jobs:
  Terraform:
    name: Terraform Init Job
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v4.3.1

    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
        client-id: 24171e0d-b632-4921-b2b1-a6576b5a075c
        tenant-id: 5642c8d6-0058-4d89-9a83-3f5de4d280b6
        subscription-id: b0805f22-5464-4af2-968e-fabac43ebd20
        
    # - name: Install Terraform
    #   uses: little-core-labs/install-terraform@v2.0.0
    #   with:
    #     version: 1.13.0 #Version of terraform to download 


      
    - name: Terraform Init
      working-directory: environment/dev
      run: terraform init -input=false

    - name: Terraform Fmt
      id: fmt
      working-directory: environment/dev
      run: terraform fmt
      # continue-on-error: true

    - name: Terraform Validate
      working-directory: environment/dev
      run: terraform validate  #-no-color

    - name: Terraform Plan
      working-directory: environment/dev
      run: terraform plan -no-color -input=false -out=tfplan.out

    - name: Terraform Show Plan Output
      working-directory: environment/dev
      run: terraform show -no-color tfplan.out

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      working-directory: environment/dev
      run: terraform apply -auto-approve tfplan.out
          
    
