name: UK_Dev_App_TodoApp_01

on:
  push:
    branches:
      - main
      - 'releases/**'
jobs:
  Terraform:
    name: Terraform Init Job
    runs-on: self-hosted
    steps:
    
    - name: Checkout
      uses: actions/checkout@v4.3.1
      
    - name: terraform init task 
      run: terraform init

    - name: terraform fmt task 
      run: terraform fmt
      
    - name: terraform validate task 
      run: terraform validate
      
    - name: terraform plan task 
      run: terraform plan
      
    - name: terraform apply task 
      run: terraform apply -auto-approve
          
    
